### ISSUE TITLE
Network Discovery disabled

### ISSUE THREAD

**Issue by TheGuyInTheChair** [gordonbay/Windows-On-Reins#5]
I'm unable to map network drives without this feature enabled. Saving changes made in the network sharing control panel do not commit. What setting can I change to enable this feature?

**Comment by gordonbay** [comment]
I`ve added the beNetworkPrinterSafe and beNetworkPrinterSafe, this may work.

**Comment by SHJordan** [comment]
Do one need to re-do creds for this to work? because whenever i try to turn on the feature, manualy, it simply didnt stick. I even tried reverting firewall rules and adding. I need to access another computer on the local network.

Tried fixes from here: https://www.elevenforum.com/t/turn-on-or-off-network-discovery-in-windows-11.4578/

Getting this error: 
![image](https://user-images.githubusercontent.com/884602/169378987-89efe678-ffc5-4969-a680-314f9515420e.png)
